### ISSUE TITLE
Portrait orientation layout

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#12]
I was wondering if you are planning a horizontal version of the app. I think this would be a great addition however getting long log messages on a horizontal view might be hard.

I think even the original log viewer on Android looks quite okay... Maybe this could be improved upon
![Screenshot_20200622-004504](https://user-images.githubusercontent.com/45742226/85236829-b6ae0600-b421-11ea-80e9-5501f1649e18.jpg)

**Comment by cyb3rko** [comment]
Good idea, I never really even thought about it.

Btw: I don't know how big your smartphone is and what browser you use, but the log in my standard browser (Chrome App) just looks terrible, that's also one of the reasons why this project was started.

**Normal view**

<img src="https://user-images.githubusercontent.com/46033730/85249055-0953e600-b453-11ea-9e0b-7e64b25aa59f.jpg" width="350">


**Desktop version**

<img src="https://user-images.githubusercontent.com/46033730/85249092-1e307980-b453-11ea-9e39-507231366875.jpg" width="350">

**Comment by felixschndr** [comment]
I am using the OnePlus 7TPro which has a huge screen and am running chrome as well.

**Comment by cyb3rko** [comment]
Ok, mine is a bit smaller. Then this is the reason why your log looks a bit better.
I will try to implement a horizontal view.

**Comment by felixschndr** [comment]
Okay, I look forward to see your implementation. When you need a test candidate hit me up =)

**Comment by cyb3rko** [comment]
Check.

**Comment by cyb3rko** [comment]
I worked on it and I think now it should work. You can test it now:

[app-debug.zip](https://github.com/nikothegreek/logviewer-for-openhab-app/files/4833304/app-debug.zip)

**Comment by felixschndr** [comment]
Love it! 
It would be nice if it automatically did rotate and the user did not have to set in the _opening screen_. Furthermore I think you can make the bezzels (on the right side and left side the space where no text is) a bit smaller so more text fits on one line
![Screenshot_20200625-212216](https://user-images.githubusercontent.com/45742226/85786041-2aa22400-b72a-11ea-9593-a10026f2c881.jpg)

**Comment by cyb3rko** [comment]
Thanks! I'm already working on the auto rotate feature, I want to be able to switch between orientation lock and auto orientation, so not everybody has to deal with an always rotating screen.

(At least currently) it is not possible for me to change anything on the website layout itself, I'm sorry.
But you can change the text size, so more text fits on one line.

More updates coming soon!

**Comment by felixschndr** [comment]
Okay =)

Maybe you can change things on the website. I just wrote an [article on the forum](https://community.openhab.org/t/change-the-look-of-the-log-viewer/101341). Maybe you can create another instance of the log and edit the appearance of that, especially regarding dark mode. However this might get pretty complicated and much hassle. So you'd have to decide if its worth it

**Comment by cyb3rko** [comment]
Sorry, I just didn't see your comment.

The problem is that changing elements on the website (like resizing the bar at the top) is complicated, I don't even know if you can do this.
Because you have to somehow change the html or css through the app code.
I am going to look for a solution, maybe there is one.

**Comment by cyb3rko** [comment]
> More updates coming soon!

I finally fixed everything, can you test the app again and tell me, if everything works as you want it to?
Thanks!

[app-debug.zip](https://github.com/cyb3rko/logviewer-for-openhab-app/files/4884063/app-debug.zip)

**Comment by felixschndr** [comment]
I tested it. However I did find out that the app reconnects to the server every time the phone gets rotated. This causes the rotation process to take quite long. See [here](https://drive.google.com/file/d/1tTJ0EdFYXGFll4oxo0N-XrNxLxPqUhFr/view?usp=sharing) and [here](https://drive.google.com/file/d/1FxVo801p3OTckfFY5GzfkSBfk1PurmDa/view?usp=sharing).

**Comment by cyb3rko** [comment]
Ok, but everything except this works fine?
I know that this happens, but that`s because the app has to be started again after you rotate your device.

I think that`s not that important, so I will first of all publish the new version and then focus on that.

It seems like your device running the log or the connection to that device is not that fast, because in my case it looks like this:
https://imgur.com/7yKyKI3

**Comment by felixschndr** [comment]
Yeah it's probably because of our crappy wifi...^^

**Comment by cyb3rko** [comment]
Oh, ok. But everything else works fine?

**Comment by felixschndr** [comment]
Yes

**Comment by cyb3rko** [comment]
Perfect, thanks a lot! Because the other test version I sent you was very buggy.
The update is coming today or tomorrow!

**Comment by cyb3rko** [comment]
Published in [Version 1.2.4](https://github.com/cyb3rko/logviewer-for-openhab-app/releases/v1.2.4)
