### ISSUE TITLE
Implement dark theme for menu (for using dark frontail theme)

### ISSUE THREAD

**Issue by cyb3rko** [cyb3rko/logviewer-for-openhab-app#14]
There is the option to change the frontail theme to dark ([see here](https://community.openhab.org/t/how-to-config-frontail-log/101197/2)), so the option to also make the LogViewer menu dark would be nice.

Btw, the dark frontail log looks like this:

<img src="https://user-images.githubusercontent.com/46033730/85406383-0562b980-b562-11ea-9748-8e63b46ad40c.jpg" width="600">

**Comment by felixschndr** [comment]
I like the black and orange theme going on. What do you want to be changed?
I think the top bar on the dark theme looks really nice
![Screenshot_20200625-213424](https://user-images.githubusercontent.com/45742226/85787440-b1a3cc00-b72b-11ea-9e15-ac8c40b69192.jpg)

**Comment by cyb3rko** [comment]
Yeah, the log already looks great with the dark frontail theme, but I want to implement a dark theme for the start menu, because the contrast between the completely white menu and the dark log is just awful...

**Comment by felixschndr** [comment]
True

**Comment by cyb3rko** [comment]
Published in [Version 2.1.0](https://github.com/cyb3rko/logviewer-for-openhab-app/releases/v2.1.0)
