### ISSUE TITLE
Multiple Text sizes

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#15]
I'd love it if there was a text size for portrait mode which would get saved and one for landscape mode. So the text could have different sized depending on the rotation for optimal reading possibility. This variable should get saved. When I now change the text size and switch the rotation the text size gets set to the default 60

**Comment by cyb3rko** [comment]
Besides the fact that you are at the moment the only one with both orientations this feature is already planned since I started to implement different orientations, but anyways thank you!

**Comment by felixschndr** [comment]
Nice =)

**Comment by cyb3rko** [comment]
You can test the feature now:

https://github.com/cyb3rko/logviewer-for-openhab-app/issues/12#issuecomment-654741077

**Comment by felixschndr** [comment]
works perfectly

**Comment by cyb3rko** [comment]
Perfect, thanks a lot!

**Comment by cyb3rko** [comment]
Published in [Version 1.2.4](https://github.com/cyb3rko/logviewer-for-openhab-app/releases/v1.2.4)
