### ISSUE TITLE
About page with some errors

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#16]
The Instagram redirection doesn't work. If you click it nothing happens. It's the same for the YouTube redirection.

**Comment by cyb3rko** [comment]
The YouTube link works perfectly fine for me.
It seems like the library I use does not work as expected, so I replaced it with own code, please try again (I uploaded new apk file).

**Comment by felixschndr** [comment]
Doesn't work yet. Same behavior as earlier

**Comment by cyb3rko** [comment]
For me both now work...

You could download [THIS APP](https://play.google.com/store/apps/details?id=com.villevalta.intentlauncher&hl=de) and write the following:

<img src="https://user-images.githubusercontent.com/46033730/87143454-64386a80-c2a6-11ea-90a4-5b799cfffdaf.jpg" width="350">

If you then click on the blue "Launch" button it should open my insta page (in the app, if you have it installed).
Does it do that?

**Comment by felixschndr** [comment]
Nevermind it works. It looks like I didn't download the most current version ^^

**Comment by cyb3rko** [comment]
Does the YouTube link work as well?

**Comment by felixschndr** [comment]
No. However this might be due to the fact that I don't have the normal YouTube app from Playstore installed

**Comment by cyb3rko** [comment]
Does at least the website open or does nothing happen?

**Comment by felixschndr** [comment]
Nothing happens

**Comment by cyb3rko** [comment]
I programmed a workaround because the library methods do not really seem to work.

**Comment by cyb3rko** [comment]
Published in [Version 1.2.5](https://github.com/nikothegreek/logviewer-for-openhab-app/releases/tag/v1.2.5)
