### ISSUE TITLE
App force closing on restart

### ISSUE THREAD

**Issue by goofy1988** [cyb3rko/logviewer-for-openhab-app#17]
**Describe the bug**
When is installed new Version (Clean Install) I set the necessary IP. port is Normal 9001. When I check connection its Ok. But then when ot tries to get into "normal" mode the app is force closing.

With 1.2.3 no issues.

Have to say I appreciate your work and effort nevertheless. 

**Smartphone:**
 - Device: [Pixel 4]
 - OS: [Android 10]
 - App Version [1.2.4]

**Comment by cyb3rko** [comment]
Thanks for your report, I am going into searching for the bug right now.
But tomorrow we will go into holidays so maybe it will take a bit longer, I'm very sorry for the circumstances.

Maybe you can use 1.2.3 until then.

Greetings!

**Comment by goofy1988** [comment]
Yes of course. I will do. Wish best holidays.

Best regards.

**Comment by cyb3rko** [comment]
I have not completely fixed it, but because you anyways use port 9001 I built a hopefully working temporary version until I will have time to finish the fix:

[LogViewer_for_openHAB_temp.zip](https://github.com/cyb3rko/logviewer-for-openhab-app/files/4950364/LogViewer_for_openHAB_temp.zip)

**Comment by goofy1988** [comment]
Thats awesome. Works flawless. Thanks alot.

**Comment by cyb3rko** [comment]
Nice to hear that it works. It's only temporary because it currently only supports port 9001 (and it's enough for your use).
That's the reason, why this issue is not already solved I'm going to reopen it again, until I release a new update where it works again.

**Comment by cyb3rko** [comment]
I think I found the bug, please try this version:

[LogViewer_for_openHAB_temp.zip](https://github.com/cyb3rko/logviewer-for-openhab-app/files/4969119/LogViewer_for_openHAB_temp.zip)

**Comment by cyb3rko** [comment]
@goofy1988 Does it work now?

**Comment by goofy1988** [comment]
Hey cyb3rko, 
I tested the new version and its working flawless. Thanks alot for trying to solve the issue so fast :-)

**Comment by cyb3rko** [comment]
Nice to hear that, thanks!

**Comment by cyb3rko** [comment]
Published in [Version 1.2.5](https://github.com/nikothegreek/logviewer-for-openhab-app/releases/tag/v1.2.5)
