### ISSUE TITLE
Buttons not centered

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#20]
Version 2.0.0-beta1

start page: connect and edit button are not centered horizontally

![Screenshot_20201027-174235](https://user-images.githubusercontent.com/45742226/97333751-2d4d8b00-187c-11eb-9d44-d10ca5eebcd4.jpg)

**Comment by cyb3rko** [comment]
Oh, it's not a bug.
I thought I would just leave the 'Connect' button there and stick the 'Edit' button right next to it, because the 'Connect' button shall be in focus and it's always enabled, while the 'Edit' button is not.

Do you think it would look better?
Then I can change it.
