### ISSUE TITLE
Center Buttons in the Log Viewer mode

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#22]
Version 2.0.0-beta1

I'd suggest do center the the "view lock" and "text size" button vertically so the space in between them is in the center of the screen on the y-axis.
Or maybe remove the back button and move one of the other two buttons to the left.
![Screenshot_20201027-174942](https://user-images.githubusercontent.com/45742226/97334518-22472a80-187d-11eb-97ef-4e4631540808.jpg)

**Comment by cyb3rko** [comment]
👍🏻 I think I will chose the first recommendation (better alignment)
