### ISSUE TITLE
Add error message when the host cant be reached

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#23]
Make the screen look nice, when the host cant be reached:

**First**: check wifi
example screenshot from openhab app
![Screenshot_20201027-175539](https://user-images.githubusercontent.com/45742226/97335209-dea0f080-187d-11eb-991f-8b81366c6677.jpg)

**Second**: ping ip/hostname to determine if host is unreachable or there is just an error with frontail
**Then**: Show error message depending on the problem

![Screenshot_20201027-090733](https://user-images.githubusercontent.com/45742226/97334800-6d613d80-187d-11eb-9c39-31a1a186af7a.jpg)

**Comment by cyb3rko** [comment]
Added to my to-do list, thanks!
