### ISSUE TITLE
Remove first back arrow

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#27]
**Describe the bug**
![Screenshot_20210125-185247](https://user-images.githubusercontent.com/45742226/105746703-12081f80-5f40-11eb-9249-d936d7e1fad7.jpg)
On the first screen when the app starts there is an unnecessary back arrow on the bottom on the left that does nothing. The arrow should only be visible starting at the second screen

**Smartphone (please complete the following information):**
 - Device: OnePlus 7T Pro
 - OS: Android 11
 - App Version: 2.0.2

**Comment by cyb3rko** [comment]
For the intro I used the library [AppIntro](https://github.com/AppIntro/AppIntro), so I can not change anything about that arrow.
But I can try to choose another style for arrows to workaround this issue.
Thanks!

**Comment by cyb3rko** [comment]
I'm sorry, but the only other option is to replace the back button with a "Skip" button. But it makes no sense in my case because you have to agree to the terms before you can continue so you can not skip the AppIntro.
Therefore it will stay like it is now.
