### ISSUE TITLE
Give example for hostname

### ISSUE THREAD

**Issue by felixschndr** [cyb3rko/logviewer-for-openhab-app#28]
I'd suggest to add an example for a hostname before the suggestion for an IP (192.168.178.10)
like `e.g. openhab or 192.168.178.10`

**Comment by cyb3rko** [comment]
I somehow forgot to include that one but I will do it on the next update.

**Comment by felixschndr** [comment]
Any progress here?

**Comment by cyb3rko** [comment]
Currently I'm quite busy and there's no update planned for this feature only.
If there will be an update for openHAB 3 soon I can include this issue here.

Greetings!
