### ISSUE TITLE
Improve Auto Scroll feature

### ISSUE THREAD

**Issue by cyb3rko** [cyb3rko/logviewer-for-openhab-app#8]
Currently the log is jumping multiple times per second to the bottom if Auto Scroll is activated.
Deactivating the ability to scroll if Auto Scroll is activated could solve this problem.

**Comment by nikothegreek** [comment]
Published in [Version 1.2.3](https://github.com/nikothegreek/logviewer-for-openhab-app/releases/tag/v1.2.3)

**Comment by cyb3rko** [comment]
Published in [Version 1.2.3](https://github.com/nikothegreek/logviewer-for-openhab-app/releases/tag/v1.2.3)
